Update updates-upgrades-rollbacks.adoc
fedora-silverblue/silverblue-docs pull request #134
Opened 2022-08-28 17:13 UTC by AndrejSh3

Included some extra information about one of the coolest features of Silverblue that no mutable distribution could ever do, and that is rebasing between different "spins" of Siverblue, as well as being able to test Silverblue Rawhide without any risk.

2022-08-29 07:35 UTC, tpopela requested changes

2022-08-29 07:35 UTC, tpopela commented on modules/ROOT/pages/updates-upgrades-rollbacks.adoc
> +Additionally, you can choose to rebase to a different variant of Silverblue, like for example Fedora Kinoite. Kinoite is similar to Silverblue, except for the fact that it uses the KDE Plasma desktop
I would replace "different variant of Silverblue" with "different immutable variant of Fedora". Also replace Gnome with GNOME.

2022-08-29 07:35 UTC, tpopela commented on modules/ROOT/pages/updates-upgrades-rollbacks.adoc
> +What this means is, you can rebase to Fedora Kinoite to try it out, without ever touching your current system. Because the two system images are isolated from eachother, you will never find your gnom
replace gnome with GNOME and apps with applications.

2022-08-30 10:13 UTC, travier reviewed
Looks reasonable to me. I'll sync this "in reverse" to the Kinoite docs too.

2022-09-02 11:27 UTC, merged